[project]
name = "safetranslate"
version = "0.1.0"
description = "Safety evaluation of machine translation for English to Chinese, Malay and Tamil health information."
readme = "README.md"
authors = [
    { name = "calvin4370", email = "calvin.j.j.chan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
